### ISSUE TITLE
3−3_imoni-manner-book.md のレビュー

### ISSUE THREAD

**Issue by RihoFUJII** [naberina/MannerBooks#3]
3−3 のレビューを書きます！
`h2` のセクションごとに書くのでご確認いただけるとうれしいです…！
Issue を書くのが初めてなので、わかりにくい部分は教えてくださると助かります 😢 

#### ① 変数を定義するには、 `const` `let` `var` といった変数宣言のキーワードを使用して変数を定義します。

- 文頭と最後尾の部分が、同じことを言っているので言い切る形にするのはどうでしょうか？
- 以下に案を書きます。

**after（案）**
> 変数を定義するには、 `const` `let` `var` といった変数宣言のキーワードを使用します。

#### ② ただし、グローバル変数は、スコープが分かりにくくなる可能性が高くなるほか、既存の値を上書きする可能性が高くなります。

- 「可能性が高くなる」という文言が繰り返されているので、まとめるといいのではないかなと思いました。
- 以下に案を書きます！
  - 「〜たり」は二回連続使うので「〜たり〜たり」としました。口語的な表現なので、案として参考程度に読んでください…！

**after（案）**
> ただし、グローバル変数は、スコープが分かりにくくなったり、既存の値を上書きしたりする可能性が高くなります。

#### ③ もっと言うと、関数なども変数に代入することができますが、ここでは、変数は何かしらの値に名前をつけて代入しておくことができる・繰り返し利用できるということを理解しておきましょう。

- 一文が長くなっているので二つの文章に分けると読みやすいかもと思いました。
- 以下に案を書きます。

**after（案）**
> もっと言うと、関数なども変数に代入することができます。
しかし、ここでは変数は何かしらの値に名前をつけて代入しておくことができる・繰り返し利用できるということを理解しておきましょう。

#### ① 変数宣言をしないとJavaScriptはグローバル変数として認識してしまします。 (`use strict`を利用している場合はエラーが返る) 繰り返し利用する値は、必ず変数宣言をしてデータを扱いましょう。

- 単純に typo をみつけました 👀 
  - 「認識してしまします」の部分です
- `use strict` を利用している場合は〜 と書いている部分のカッコは前の文章を補完するものでしょうか？
  - もし認識があっていれば、句点の前にカッコを書くといいと思います！
- 上記 2 点を踏まえて、以下に案を書きます！

**after（案）**
> 変数宣言をしないとJavaScriptはグローバル変数として認識してしまいます (`use strict`を利用している場合はエラーが返る) 。繰り返し利用する値は、必ず変数宣言をしてデータを扱いましょう。

**Comment by naberina** [comment]
@RihoFUJII 
ありがとうございます！
納得感しかないです🙏

修正しました！
https://github.com/naberina/MannerBooks/pull/7
