### ISSUE TITLE
3-5_imoni-manner-book.md のレビュー

### ISSUE THREAD

**Issue by RihoFUJII** [naberina/MannerBooks#5]
3−5 のレビューを書きます！
3−3 のレビューに引き続き、 `h2` のセクションごとに書きますのでご確認お願いします 🙇🏻 

#### L.25「ECMAScript 2015 における予約キーワード」 のリンク
- 突然リンクが出てきた感があったので、 `参照` や `Ref.` などをつけるとわかりやすいかなと思いました。
- 以下に案を書きます！

**after（案）**
> Ref. [ECMAScript 2015 における予約キーワード](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Lexical_grammar#keywords)

**Comment by naberina** [comment]
`Ref. ` 良いですね！
一気に表現がカッコいいですし、
「どういう意味だろう？」と思った人には検索して欲しいので採用します！
